name: Manually trigger an Azure Machine Learning job

on: [push]

jobs:
  train_dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Train model
        run: |
          az ml job create --file ./src/experiment_train.yml -w ${{vars.AZURE_ML_WORKSPACE}} -g ${{vars.AZURE_ML_RESOURCE_GROUP}} --stream
  train_prod:
    needs: [train_dev]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Train model
        run: |
          az ml job create --file ./src/prod_train.yml -w ${{vars.AZURE_ML_WORKSPACE}} -g ${{vars.AZURE_ML_RESOURCE_GROUP}} --stream
      
